---
title: OAuth Client Credentials Login Flow
description: Client credentials grant login without a client library.
categories:
- OAuth
steps:
- title: Introduction
  content: |
    This tutorial walks through the steps of using the OAuth client credentials grant.  For more information on using implicit grant, see [Use a Client Credentials Grant](http://developer.inindca.com/api/rest/authorization/use-client-credentials.html).

    The client credentials grant is useful in applications without a user interface that do not make API calls on behalf of a user. This means that if you log in using the client credentials grant, you cannot use operations like /api/v2/users/me because the application is not running as a user.

- title: Obtain an Access Token
  content: |
    Start by making a POST call https://login.mypurecloud.com/oauth/token with the following settings:

    * Authentication- Basic
    * User- Client ID
    * Password- Client secret

    To use basic authentication, set the authentication header to ```Basic <base64EncodedUserPass>```, where base64EncodedUserPass is a base64-encoded string containing the username and password separated by a colon: base64(user:password)

    Some languages handle the basic authentication. Other languages require you to encode the header as base64.

- title: Make API Calls
  content: |
    The response of the POST contains the access token. Include this token in the authorization header of API calls.

languages:
  ruby:
    displayName: Ruby
    steps:
    - file: "ruby/script.rb"
      highlight: "0-100"
    - file: "ruby/script.rb"
      highlight: "5-15"
    - file: "ruby/script.rb"
      highlight: "17-21"
  nodejs:
    displayName: NodeJS
    steps:
    - file: "nodejs/script.js"
      highlight: "0-100"
    - file: "nodejs/script.js"
      highlight: "20-28"
    - file: "nodejs/script.js"
      highlight: "3-18"
  powershell:
    displayName: PowerShell
    steps:
    - file: "powershell/script.ps1"
      highlight: "0-100"
    - file: "powershell/script.ps1"
      highlight: "1-7"
    - file: "powershell/script.ps1"
      highlight: "8-12"
  python:
    displayName: Python
    steps:
    - file: "python/script.py"
      highlight: "0-54"
    - file: "python/script.py"
      highlight: "7-22"
    - file: "python/script.py"
      highlight: "31-52"
  go:
    displayName: Go
    steps: 
    - file: "go/main.go"
      highlight: "0-150"
    - file: "go/main.go"
      highlight: "24-59"
    - file: "go/main.go"
      highlight: "61-95"
