---
title: Automatic SMS after Call
description: Automatically send SMS after a call gets disconnected using Platform API.
categories:
- Architect
steps:
- title: Introduction
  content: |
    The main objective of this tutorial is to showcase how to create an interaction, and send SMS through a queue with Platform API. The given sample code will send a message after an agent drops off a call. This tutorial will also cover how to create a notification channel, subscribe to a topic and listen to a web socket.
- title: Authenticate with Genesys Cloud
  content: |
    First, authenticate the application with Genesys Cloud.

    More details about authentication [here](https://developer.mypurecloud.com/api/rest/authorization/).
- title: Create a Notification Channel 
  content: |
    Create a notification channel and subscribe to the topic `{"id": "v2.routing.queues.{queueID}.conversations.calls"}`. This topic will listen to a queues incoming and outgoing calls. After setting up the notification channel, create a web socket object using the notification channel URI.
- title: Recieving Notification
  content: |
    Every time a call connects to the queue a notification will be sent to the web socket. An attribute is also added to the customers information after a message is sent, this is done later on the sample. This will be filtered too, to avoid sending multiple SMS to the customer.
- title: Create Conversation
  content: |
    Create a new conversation and get the conversation ID and communication ID.
    If an there is an existing SMS conversation with the external customer, then use it instead.
- title: Send SMS
  content: |
    Send the SMS message and update the customer's attribute on the call conversation.

languages: 
  nodejs:
    displayName: Javascript
    steps:
    - file: "javascript/index.html"
      highlight: "0-156"
    - file: "javascript/index.html"
      highlight: "38-42"
    - file: "javascript/index.html"
      highlight: "47-65"
    - file: "javascript/index.html"
      highlight: "70-104"
    - file: "javascript/index.html"
      highlight: "107-123"
    - file: "javascript/index.html"
      highlight: "126-148"
    