---
title: Creating External Contacts
description: Overview of creating External Contacts from a CSV file
categories:
- Contacts
steps:
- title: Introduction
  content: |
    External Contacts is a comprehensive repository of data about your external organizations and contacts. You can see a streamlined view of all contact and organization data and start a call, send an email, or visit a contact’s website directly from a contact’s record.

    Loading external contacts doesn't have to be a manual process and this tutorial will walk through the steps of creating external contacts sourced by a csv file.

    For more information on external contacts see the [Resource Center](https://help.mypurecloud.com/articles/about-external-contacts/)

- title: Authenticate with Genesys Cloud
  content: |
    The OAuth Client Credentials are retrieved from environment variables and used to authenticate with Genesys Cloud.

- title: Create an Organization
  content: |
    The first thing we are going to do is create a new organization which all of our contacts will be a part of.

    We can create the ExternalOrganization entity, specifiying the fields that are relevant to our use case, and then call postExternalcontactsOrganizations to create the organization.

    The response from this post will contain an id property which we will use to associate our contacts to this organization.

- title: Create Users
  content: |
    After we read our csv file we can iterate over each contact. In our csv file the first row is the colum names so we will start at index = 1.

    In order to tie the new contact to the organization we just created, we need to set the organization id to the externalOrganization.id property of the new contact.

    Once we have the new contact created, we can call postExternalcontactsContacts and create the contact.

languages:
  nodejs:
    displayName: NodeJS
    steps:
    - file: "nodejs/index.js"
      highlight: "0-100"
    - file: "nodejs/index.js"
      highlight: "5-20"
    - file: "nodejs/index.js"
      highlight: "22-45"
    - file: "nodejs/index.js"
      highlight: "47-82"
  python:
    displayName: Python
    steps:
    - file: "python/external-contacts.py"
      highlight: "0-67"
    - file: "python/external-contacts.py"
      highlight: "10-11"
    - file: "python/external-contacts.py"
      highlight: "16-38"
    - file: "python/external-contacts.py"
      highlight: "40-66"
