# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Auth Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS Auth Tutorial
  pod 'PureCloudPlatformClientV2', :git => 'https://github.com/MyPureCloud/platform-client-sdk-ios.git', :tag => '2.0.4'

end
